In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

sns.set()

# I/ Importation des données

### I.A/ Fichiers uniques

In [14]:
# Import des données
df_sales = pd.read_csv("../DATA/df_sales.csv")
df_events = pd.read_csv("../DATA/df_events.csv")
df_customers = pd.read_csv("../DATA/df_customers.csv")

# Suppression des colonnes inutiles
df_sales = df_sales[df_sales.columns.drop(['Unnamed: 0'])]
df_customers=df_customers[df_customers.columns.drop(['Unnamed: 0'])]
df_events=df_events[df_events.columns.drop(['Unnamed: 0'])]

# Conversion des types
df_sales['id_client']=df_sales['id_client'].astype(str)
df_customers['ID']=df_customers['ID'].astype(str)

df_sales.head()

,id_billet,commande,date_creation,id_client,prix,date_utilisation,source
0,0,0,2024-05-20 23:38:17,3753,7.99,2024-06-08 01:09:18,CRM240608
1,1,1,2024-05-21 01:11:17,1323,7.99,2024-06-08 01:55:08,CRM240608
2,2,2,2024-05-21 01:27:30,3743,7.99,2024-06-08 00:11:39,CRM240608
3,3,3,2024-05-21 01:29:29,1432,7.99,2024-06-08 00:11:47,CRM240608
4,4,4,2024-05-21 01:35:59,4657,7.99,2024-06-08 00:30:54,CRM240608

### I.B/ Jointure des données

In [15]:
# Jointure des données
df_temp = pd.merge(left=df_sales, right=df_events, left_on='source', right_on='Source')
df_temp = pd.merge(left=df_temp, right=df_customers, left_on='id_client', right_on='ID')
print(f"Nombre de lignes : {df_temp.shape[0]}")
df_temp.head()

Nombre de lignes : 13703

,id_billet,commande,date_creation,id_client,prix,date_utilisation,source,ID_x,begin_on,ville,Source,Lieu,Type_Lieu,ID_y,sexe,DDN,sub,sub_notif,sub_newsletter
0,0,0,2024-05-20 23:38:17,3753,7.99,2024-06-08 01:09:18,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,3753,F,2005-05-19,NaN,NaN,NaN
1,1,1,2024-05-21 01:11:17,1323,7.99,2024-06-08 01:55:08,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,1323,F,2003-01-01,0.0,0.0,0.0
2,2,2,2024-05-21 01:27:30,3743,7.99,2024-06-08 00:11:39,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,3743,F,NaN,NaN,NaN,NaN
3,3,3,2024-05-21 01:29:29,1432,7.99,2024-06-08 00:11:47,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,1432,F,2005-01-01,0.0,0.0,0.0
4,4,4,2024-05-21 01:35:59,4657,7.99,2024-06-08 00:30:54,CRM240608,17,2024-06-07,Lille,CRM240608,Salle Verte,Club,4657,NaN,2001-01-01,0.0,0.0,0.0

# II/ Préparation des données

### II.A/ Conversion des types

In [16]:
# Suppression des colonnes superflues
drop_columns = ['ID_x', 'ID_y']
df_work = df_temp[df_temp.columns.drop(drop_columns)]

# Changement des types
df_work['date_creation'] = pd.to_datetime(df_work['date_creation'])
df_work['date_utilisation'] = pd.to_datetime(df_work['date_utilisation'])
df_work['begin_on'] = pd.to_datetime(df_work['begin_on'])
df_work['DDN'] = pd.to_datetime(df_work['DDN'])

df_work.head()

/tmp/ipykernel_14087/1292748174.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['date_creation'] = pd.to_datetime(df_work['date_creation'])
/tmp/ipykernel_14087/1292748174.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['date_utilisation'] = pd.to_datetime(df_work['date_utilisation'])
/tmp/ipykernel_14087/1292748174.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['begin_on'] = pd.to_datetime(df_work['begin_on'])
/tmp/ipykernel_14087/1292748174.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['DDN'] = pd.to_datetime(df_work['DDN'])

,id_billet,commande,date_creation,id_client,prix,date_utilisation,source,begin_on,ville,Source,Lieu,Type_Lieu,sexe,DDN,sub,sub_notif,sub_newsletter
0,0,0,2024-05-20 23:38:17,3753,7.99,2024-06-08 01:09:18,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,2005-05-19,NaN,NaN,NaN
1,1,1,2024-05-21 01:11:17,1323,7.99,2024-06-08 01:55:08,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,2003-01-01,0.0,0.0,0.0
2,2,2,2024-05-21 01:27:30,3743,7.99,2024-06-08 00:11:39,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,NaT,NaN,NaN,NaN
3,3,3,2024-05-21 01:29:29,1432,7.99,2024-06-08 00:11:47,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,F,2005-01-01,0.0,0.0,0.0
4,4,4,2024-05-21 01:35:59,4657,7.99,2024-06-08 00:30:54,CRM240608,2024-06-07,Lille,CRM240608,Salle Verte,Club,NaN,2001-01-01,0.0,0.0,0.0

In [17]:
# Affichage des types 
df_work.dtypes

id_billet                    int64
commande                     int64
date_creation       datetime64[ns]
id_client                   object
prix                       float64
date_utilisation    datetime64[ns]
source                      object
begin_on            datetime64[ns]
ville                       object
Source                      object
Lieu                        object
Type_Lieu                   object
sexe                        object
DDN                 datetime64[ns]
sub                        float64
sub_notif                  float64
sub_newsletter             float64
dtype: object

### II.B/ Traitement des valeurs nulles

In [18]:
# Affichage des taux de remplissage des 
df_work.notnull().mean()

id_billet           1.000000
commande            1.000000
date_creation       1.000000
id_client           1.000000
prix                1.000000
date_utilisation    0.799241
source              1.000000
begin_on            1.000000
ville               1.000000
Source              1.000000
Lieu                1.000000
Type_Lieu           1.000000
sexe                0.872510
DDN                 0.856820
sub                 0.356053
sub_notif           0.356053
sub_newsletter      0.380793
dtype: float64

In [19]:
### Date utilisation
# Calcule des médianes groupées
df_work['date_utilisation'] = df_work['date_utilisation'].fillna(
    df_work.groupby('source')['date_utilisation']
           .transform(lambda x: x.dropna().median())
)

### Sexe
df_work['sexe']=df_work['sexe'].replace({'1':'F', '0':'M'}) # Formatage des données pour n'avoir que 2 modalités
df_work['sexe']=df_work['sexe'].fillna(value=df_work['sexe'].mode()[0])

### DDN
df_work['DDN']=df_work['DDN'].fillna(df_work['DDN'].median())

### sub, sub_notif, sub_newsletter
df_work['sub']=df_work['sub'].fillna(0)
df_work['sub_notif']=df_work['sub_notif'].fillna(0)
df_work['sub_newsletter']=df_work['sub_newsletter'].fillna(0)

/tmp/ipykernel_14087/2936186222.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['date_utilisation'] = df_work['date_utilisation'].fillna(
/tmp/ipykernel_14087/2936186222.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sexe']=df_work['sexe'].replace({'1':'F', '0':'M'}) # Formatage des données pour n'avoir que 2 modalités
/tmp/ipykernel_14087/2936186222.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sexe']=df_work['sexe'].fillna(value=df_work['sexe'].mode()[0])
/tmp/ipykernel_14087/2936186222.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['DDN']=df_work['DDN'].fillna(df_work['DDN'].median())
/tmp/ipykernel_14087/2936186222.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sub']=df_work['sub'].fillna(0)
/tmp/ipykernel_14087/2936186222.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sub_notif']=df_work['sub_notif'].fillna(0)
/tmp/ipykernel_14087/2936186222.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['sub_newsletter']=df_work['sub_newsletter'].fillna(0)